Document: libitute164
Title: Debian libitute164 Manual
Author: <insert document author here>
Abstract: This manual describes what libitute164 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libitute164/libitute164.sgml.gz

Format: postscript
Files: /usr/share/doc/libitute164/libitute164.ps.gz

Format: text
Files: /usr/share/doc/libitute164/libitute164.text.gz

Format: HTML
Index: /usr/share/doc/libitute164/html/index.html
Files: /usr/share/doc/libitute164/html/*.html
